apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: upskill-api-dev
  namespace: argocd
spec:
  project: upskill
  source:
    repoURL: git@github.com:Dumberdore/homelab-gitops.git
    targetRevision: main
    path: apps/upskill-api/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: upskill-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - PruneLast=true
