apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: upskill-namespaces
  namespace: argocd
spec:
  project: upskill
  source:
    repoURL: https://github.com/Dumberdore/homelab-gitops.git
    targetRevision: main
    path: platform/namespaces
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - PruneLast=true
