apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: upskill-postgres-staging
  namespace: argocd
spec:
  project: upskill
  source:
    repoURL: https://github.com/Dumberdore/homelab-gitops.git
    targetRevision: main
    path: apps/postgres/overlays/staging
  destination:
    server: https://kubernetes.default.svc
    namespace: upskill-staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - PruneLast=true
