apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: upskill-postgres-prod
  namespace: argocd
spec:
  project: upskill
  source:
    repoURL: git@github.com:Dumberdore/homelab-gitops.git
    targetRevision: main
    path: apps/postgres/overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: upskill-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - PruneLast=true
